force-app/main/default/objects/Order__b/Order__b.object-meta.xml
<CustomObject>
    <label>Order</label>
    <pluralLabel>Orders</pluralLabel>
</CustomObject>

force-app/main/default/objects/Order__b/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account Id</description>
    <inlineHelpText>Standard Account Reference</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__b/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount for this order.</description>
    <inlineHelpText>Amount for this order.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__b/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__b/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <label>Product Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__b/fields/Transaction_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Transaction_DateTime__c</fullName>
    <label>Transaction DateTime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/SalesOrderController.cls
public with sharing class SalesOrderController {
    public SalesOrderController() {

    }
    @AuraEnabled
    public static List<Order__b> getOrders (String accountId) {
        List<Account> acctRecord = new List<Account>();
        List<Case> caseRecord = new List<Case>();
        String recordId;
        //check if the id is invoked from case or account object.
        //currently, it is supported only in account and case record pages.
        String recordIdentifier = accountId.left(3);
        System.debug(LoggingLevel.debug, '---> record identifier ' + recordIdentifier);
        if(recordIdentifier.equals('001')) {
            acctRecord = [SELECT Id, Name FROM Account WHERE Id = :accountId LIMIT 1];
            recordId = acctRecord[0].Id;
        }else if(recordIdentifier.equals('500')) {
            caseRecord = [SELECT Id, AccountId FROM Case WHERE Id = :accountId LIMIT 1];
            recordId = caseRecord[0].AccountId;
        }

        System.debug(LoggingLevel.debug, '---> record Id ' + recordId);
        List<Order__b> orders = [SELECT Id, Account__c, Amount__c, Channel__c, Product_Id__c, Transaction_DateTime__c
                            FROM Order__b
                            WHERE Account__c = :recordId];
        return orders;
    }
}